events{

}


http{

    upstream backend {  # upstream <variable_name>  
        server server1:7000 ;    #  server <server-name>:<container-port>
        server server2:7000 ;
        server server3:7000 ;
    }

    server{
        listen 80 ;     # listen <which port nginx is running inside container>
        location /{     # location <which route of nginx>
            # Telling where to go if this route (http://localhost:8000/) is hit


            # using nginx has web server by serving the content at (http://localhost:8000/)
            # return 200 "hello from sushant" ; # return <status> <message>


            # using nginx as a loadbalancer
                # proxy_pass http://server1:7000 ;    # proxy_pass http://<server-name>:<container-port> 


            # mapping servers with loadbalancer using variable name (backend)
            proxy_pass http://backend ;
        }
    }
}
